### PR TITLE
Owasp top10 2017 apps/a10/games irados

### PR DESCRIPTION
**Pull request by thiagolotufo**
## This solution refers to which of the apps?

A/M# - owasp-top10-2017-apps/a10/games-irados

## What did you do to mitigate the vulnerability?

The main vulnerability of this application is logs with little information. To mitigate this vulnerability, I created customized logs with important information for registration.

## Did you test your changes? What commands did you run?

For testing, I made some requests with different information and routes. The generated logs returned with important information for registration.

- In this case, I used the application search, with the value 123. The log returns with the route, the method, the date, the IP of the request and the value of the input.

Screen Shot 2021-04-15 at 17 57 41

### CODE REVIEW

**Comment by gustavocovas** [comment]
Hey, @thiagolotufo! Nice work improving the logs there. However, a couple things are missing. Lets take a look at a log line:

```
2021-04-16 14:05:34,739 POST /coupon 172.22.0.3 b'teste1' INPUT 200
```

- How can we tell what happened? We would like to known if the user applied the coupon successfully. Logging the HTTP status return and some short string describing what happened should be sufficient
- How can we distinguish each field? In this case, I know that `teste1` is the user performing the request, but this may not be obvious for another person inspecting these logs. What is `INPUT`? We could use some `key=value` structure or even short sentences
- What about the log in / log out events? We want to monitor and detect if someone is trying to brute-force their way in some account
- I suspect that `172.22.0.3` is the server IP address, not the client one. [Flask can help you there](https://flask.palletsprojects.com/en/1.1.x/api/#incoming-request-data). Take a look at the `remote_addr` in the [Request object](https://werkzeug.palletsprojects.com/en/1.0.x/wrappers/#werkzeug.wrappers.Request)

**Comment by thiagolotufo** [comment]
Hi @gustavocovas,

I have corrected the points you mentioned in your review.
The data may change according to the route and user information.
Now, the log format looks like this:

> 2021-04-19 15:02:08,678 METHOD: POST - STATUS: 404 - Cupom invalido - ROUTE: /coupon - IP: 172.22.0.1 - USER: b'admin' STATUS LOG

**Comment by gustavocovas** [comment]
Nice, this log format is way more informative!

However I got an error when signing up, can you take a look at that?

```
Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2309, in __call__

return self.wsgi_app(environ, start_response)

File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2295, in wsgi_app

response = self.handle_exception(e)

File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1741, in handle_exception

reraise(exc_type, exc_value, tb)

File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 35, in reraise

raise value

File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2292, in wsgi_app

response = self.full_dispatch_request()

File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1815, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1718, in handle_user_exception

reraise(exc_type, exc_value, tb)

File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 35, in reraise

raise value

File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1813, in full_dispatch_request

rv = self.dispatch_request()

File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "/app/routes.py", line 116, in newuser

loggingOut(request.method,'/register', username, status, response.method)

NameError: name 'response' is not defined
```

I also noticed that you are logging what appears to be HTTP status codes. Take a login failure, for example:

```python
status = str(401)+" - Usuario ou senha incorretos"
loggingOut(request.method,'/login', username, status)
```

But the application does not return a 401 status in this case. It returns a 200, and the error is indicated for the user in the UI. This is usual with server rendered pages. In this case, I think the short description of what happened should be sufficient. :smile:

**Comment by gustavocovas** [comment]
Cool, now the service works and the logs are informative. Way to go! 🚀 🐼

**Pull request closed without merging**
