### PR TITLE
WIP: add a1 - Command Injection - cowsay

### PR DESCRIPTION
**Pull request by v0idpwn**
As straightforward as it can be, I guess :)

### CODE REVIEW

**Comment by v0idpwn** [comment]
Related to #277. Implemented in python with flask.

**Comment by Krlier** [comment]
> Related to #277. Implemented in python with flask. This is a WIP pull request. I still have to port it to Docker Compose and the file structure. I'll try to do it today.

Hey, @v0idpwn! How are you doing?

How can I help you with this PR?

**Comment by v0idpwn** [comment]
Krlier: I got quite lost with the Docker/Make stuff. I'll check it out soon.

**Comment by rafaveira3** [comment]
Closing this for now! Feel free to reopen this PR if you are still working on this. 🙃

**Pull request closed without merging**
