### PR TITLE
Add improve to log structure

### PR DESCRIPTION
**Pull request by danilogila**
Add improve to log structure in order to mitigate

### CODE REVIEW

**Comment by danilogila** [comment]
@vitoriario I made some changes at my code. Could take a look?

**Comment by vitoriario** [comment]
@danilogila, You splited your log parameters into smaller ones. This could be a problem due the concurrency: If 2 requests are made at the same time the log timeline would be confused.

Also, you are forgetting to answer some question like: Who, Where, How...
Take a look at the slides, there is an exemple of a good log structure.

**Comment by danilogila** [comment]
@vitoriario Fixed my log structure. Could you take a look at it?

**Comment by rafaveira3** [comment]
Hey, @danilogila . I was not able to build your app after your last commit: 
```sh
$ docker logs -f app-a10
  File "routes.py", line 104
    logger.error(dict(
    ^
IndentationError: unexpected indent
  File "routes.py", line 104
    logger.error(dict(
    ^
IndentationError: unexpected indent
  File "routes.py", line 104
    logger.error(dict(
    ^
IndentationError: unexpected indent
  File "routes.py", line 104
    logger.error(dict(
    ^
IndentationError: unexpected indent
  File "routes.py", line 104
    logger.error(dict(
    ^
IndentationError: unexpected indent
  File "routes.py", line 104
    logger.error(dict(
    ^
IndentationError: unexpected indent
  File "routes.py", line 104
    logger.error(dict(
    ^
IndentationError: unexpected indent
  File "routes.py", line 104
    logger.error(dict(
    ^
IndentationError: unexpected indent
  File "routes.py", line 104
    logger.error(dict(
    ^
IndentationError: unexpected indent
```

Would you mind confirming this, please?

**Comment by danilogila** [comment]
@rafaveira3 I made some changes. Could you take a look at it?

**Comment by rafaveira3** [comment]
Awesome, @danilogila ! You rock!! 🔥

**Pull request closed without merging**
